# yamllint disable rule:line-length
---
version: '3.8'
services:
  intekenontvanger-generiek:
    image: ghcr.io/surfnet/student-mobility-intekenontvanger-email/intekenontvanger-email:latest
    volumes:
      - ${PWD}/application.yml:/application.yml
    ports:
      - 8093:8093
